# Generated by Django 2.1.5 on 2019-01-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationanswer',
            name='address',
            field=models.CharField(max_length=255, verbose_name='adresa'),
        ),
        migrations.AlterField(
            model_name='registrationanswer',
            name='child_brith_date',
            field=models.DateField(help_text='Ve formátu D.M.RRRR, např. 15.4.2013', verbose_name='datum narození dítěte'),
        ),
        migrations.AlterField(
            model_name='registrationanswer',
            name='child_name',
            field=models.CharField(max_length=100, verbose_name='jméno dítěte'),
        ),
        migrations.AlterField(
            model_name='registrationanswer',
            name='contact',
            field=models.CharField(max_length=255, verbose_name='kontakt'),
        ),
        migrations.AlterField(
            model_name='registrationanswer',
            name='email',
            field=models.EmailField(help_text='Na tuto e-mailovou adresu obdržíte potvrzení o termínu zápisu.', max_length=254, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='registrationanswer',
            name='identifier',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='přidělený identifikátor'),
        ),
        migrations.AlterField(
            model_name='registrationanswer',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='interní poznámka'),
        ),
        migrations.AlterField(
            model_name='registrationanswer',
            name='parent_name',
            field=models.CharField(max_length=100, verbose_name='jméno zákonného zástupce'),
        ),
        migrations.AlterUniqueTogether(
            name='registrationanswer',
            unique_together={('child_name', 'child_brith_date')},
        ),
    ]
