# Generated by Django 2.1.5 on 2019-01-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regform', '0002_auto_20190114_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationanswer',
            name='email_sent',
            field=models.BooleanField(blank=True, default=False, verbose_name='e-mail byl úspěšně odeslán'),
        ),
    ]
