# Generated by Django 2.1.5 on 2019-01-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regform', '0003_registrationanswer_email_sent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrationanswer',
            options={'verbose_name': 'Odpovědi z registrace', 'verbose_name_plural': 'Odpovědi z registrace'},
        ),
        migrations.AlterModelOptions(
            name='registrationdate',
            options={'ordering': ['date'], 'verbose_name': 'Termíny pro registraci', 'verbose_name_plural': 'Termíny pro registraci'},
        ),
        migrations.RemoveField(
            model_name='registrationdate',
            name='available',
        ),
        migrations.AlterField(
            model_name='registrationanswer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno'),
        ),
        migrations.AlterField(
            model_name='registrationanswer',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Změněno'),
        ),
        migrations.AlterField(
            model_name='registrationdate',
            name='date',
            field=models.DateTimeField(verbose_name='Termín'),
        ),
        migrations.AlterUniqueTogether(
            name='registrationanswer',
            unique_together=set(),
        ),
    ]
