# Generated by Django 2.1.5 on 2019-01-16 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regform', '0004_auto_20190114_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationanswer',
            name='reg_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regform.RegistrationDate', verbose_name='Termín pro registraci'),
        ),
    ]
