# Generated by Django 2.1.5 on 2019-01-16 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regform', '0005_auto_20190116_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationanswer',
            name='reg_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regform.RegistrationDate', unique=True, verbose_name='Termín pro registraci'),
        ),
    ]
