# Generated by Django 2.1.5 on 2019-01-18 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regform', '0010_substitutecontact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='substitutecontact',
            options={'verbose_name': 'Evidence náhradníků', 'verbose_name_plural': 'Evidence náhradníků'},
        ),
    ]
