# Generated by Django 2.1.15 on 2023-01-31 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regform', '0011_auto_20190118_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationanswer',
            name='possible_postponement',
            field=models.PositiveSmallIntegerField(choices=[(0, 'neznámo'), (10, 'ano'), (20, 'ne')], default=0, verbose_name='zvažujete odklad školní docházky?'),
        ),
        migrations.AlterField(
            model_name='registrationanswer',
            name='address',
            field=models.CharField(max_length=255, verbose_name='adresa trvalého bydliště'),
        ),
        migrations.AlterField(
            model_name='registrationanswer',
            name='child_name',
            field=models.CharField(max_length=100, verbose_name='jméno a příjmení dítěte'),
        ),
        migrations.AlterField(
            model_name='registrationanswer',
            name='parent_name',
            field=models.CharField(max_length=100, verbose_name='jméno a příjmení zákonného zástupce'),
        ),
    ]
