# Generated by Django 2.1.15 on 2023-01-31 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regform', '0012_auto_20230131_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationanswer',
            name='substitute',
            field=models.BooleanField(default=False, verbose_name='náhradník'),
        ),
    ]
