# Generated by Django 3.0.14 on 2025-02-02 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regform', '0014_auto_20230131_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationanswer',
            name='child_birth_date',
            field=models.DateField(help_text='Ve formátu D.M.RRRR, např. 15.4.2013', verbose_name='datum narození'),
        ),
    ]
